version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=pbl
      - POSTGRES_USER=bismillah
      - POSTGRES_PASSWORD=bismillah

  web:
    build: .
    command: gunicorn --config gunicorn_config.py config.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
